apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: ${namespace} 
data:
  registries.conf: |
    registries:
    - name: Google Container Registry
      api_url: ${registry} 
      prefix: europe-central2-docker.pkg.dev
      ping: no
      credentials: pullsecret:${namespace}/${credential} 